// src/components/admin/LoginForm.vue
<script setup>
import './LoginForm.css'
import { ref } from 'vue'

// Eventos hacia el padre
const emit = defineEmits(['login-exitoso', 'acceso-restringido'])

// Estado del formulario
const usuario = ref('')
const contrasena = ref('')
const error = ref('')
const cargando = ref(false)

/**
 * Maneja el submit del formulario.
 * Hace fetch async de /usuarios.json, busca credenciales y emite
 * el evento correspondiente según el resultado.
 */
async function handleSubmit() {
  error.value = ''
  cargando.value = true

  try {
    const respuesta = await fetch('/usuarios.json')
    if (!respuesta.ok) throw new Error('No se pudo cargar la base de usuarios.')

    const usuarios = await respuesta.json()

    const encontrado = usuarios.find(
      (u) => u.name === usuario.value && u.password === contrasena.value
    )

    if (!encontrado) {
      error.value = 'Credenciales inválidas. Revisá usuario y contraseña.'
      return
    }

    if (!encontrado.isAdmin) {
      // Usuario existe pero no tiene permisos de admin
      emit('acceso-restringido', encontrado)
      return
    }

    // Admin legítimo
    emit('login-exitoso', encontrado)
  } catch (e) {
    error.value = 'Error al verificar credenciales: ' + e.message
  } finally {
    cargando.value = false
  }
}
</script>

<template>
  <div class="login-wrapper">
    <div class="login-ficha">
      <div class="login-cabecera">
        <span class="login-stamp">Sistema de gestión</span>
        <h1 class="login-titulo">
          Panel<br>Admin
        </h1>
      </div>

      <form
        class="login-form"
        @submit.prevent="handleSubmit"
      >
        <div class="login-campo">
          <label
            for="login-usuario"
            class="login-label"
          >Usuario</label>
          <input
            id="login-usuario"
            v-model="usuario"
            type="text"
            class="login-input"
            autocomplete="username"
            placeholder="nombre de usuario"
            required
          >
        </div>

        <div class="login-campo">
          <label
            for="login-contrasena"
            class="login-label"
          >Contraseña</label>
          <input
            id="login-contrasena"
            v-model="contrasena"
            type="password"
            class="login-input"
            autocomplete="current-password"
            placeholder="••••••••"
            required
          >
        </div>

        <!-- Error de credenciales — feedback inmediato en el mismo form -->
        <div
          v-if="error"
          class="login-error"
          role="alert"
        >
          <em class="login-error-icono">!</em>
          {{ error }}
        </div>

        <div class="login-submit">
          <button
            type="submit"
            class="btn-brutal btn-brutal--accent login-btn"
            :class="{ 'login-btn--cargando': cargando }"
            :disabled="cargando"
          >
            {{ cargando ? 'Verificando...' : 'Ingresar al panel' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

// src/components/admin/LoginForm.jsx
/**
 * LoginForm — formulario de autenticación del panel admin.
 * Estética de ficha/carnet: centrado, sombra dura grande, bordes rectos.
 */
import { useState } from 'react';
import './LoginForm.css';

export default function LoginForm({ onLoginExitoso, onLoginBloqueado }) {
  const [usuario, setUsuario] = useState('');
  const [contrasena, setContrasena] = useState('');
  const [cargando, setCargando] = useState(false);
  const [error, setError] = useState('');

  async function handleSubmit(e) {
    e.preventDefault();
    setError('');
    setCargando(true);

    try {
      const res = await fetch('/usuarios.json');
      const usuarios = await res.json();

      // Comparar credenciales con el listado
      const encontrado = usuarios.find(
        (u) => u.name === usuario.trim() && u.password === contrasena
      );

      if (!encontrado) {
        setError('Credenciales inválidas. Revisá usuario y contraseña.');
        setCargando(false);
        return;
      }

      if (!encontrado.isAdmin) {
        // Usuario válido pero sin permiso admin
        onLoginBloqueado(encontrado);
        return;
      }

      // Admin confirmado
      onLoginExitoso(encontrado);
    } catch {
      setError('Error al conectar con el servidor. Intentá de nuevo.');
    } finally {
      setCargando(false);
    }
  }

  return (
    <div className="login-wrapper">
      <div className="login-ficha">
        {/* Encabezado tipo sello de imprenta */}
        <div className="login-header">
          <span className="login-stamp">PANEL DE CONTROL</span>
          <h1 className="login-titulo">ADMIN</h1>
          <p className="login-subtitulo">Acceso restringido al sistema</p>
        </div>

        <form className="login-form" onSubmit={handleSubmit} noValidate>
          <div className="login-campo">
            <label className="login-label" htmlFor="login-usuario">
              USUARIO
            </label>
            <input
              id="login-usuario"
              className="login-input"
              type="text"
              value={usuario}
              onChange={(e) => setUsuario(e.target.value)}
              autoComplete="username"
              placeholder="nombre de usuario"
              required
            />
          </div>

          <div className="login-campo">
            <label className="login-label" htmlFor="login-contrasena">
              CONTRASEÑA
            </label>
            <input
              id="login-contrasena"
              className="login-input"
              type="password"
              value={contrasena}
              onChange={(e) => setContrasena(e.target.value)}
              autoComplete="current-password"
              placeholder="••••••••"
              required
            />
          </div>

          {/* Mensaje de error duro */}
          {error && (
            <div className="login-error" role="alert">
              <span className="login-error-icono">!</span>
              {error}
            </div>
          )}

          <button
            type="submit"
            className="btn-brutal btn-brutal--accent login-btn"
            disabled={cargando}
          >
            {cargando ? 'VERIFICANDO...' : 'INGRESAR AL PANEL'}
          </button>
        </form>

        {/* Pie de la ficha */}
        <div className="login-pie">
          <span className="tag-brutal">UMAI · 2026</span>
        </div>
      </div>
    </div>
  );
}
