// src/components/admin/TablaContenido.jsx
/**
 * TablaContenido — CRUD completo sobre el array de contenido.
 * Operaciones: Agregar, Editar (carga en formulario), Borrar (con confirmación inline).
 * Cada acción instancia AdminRequest y registra en historial.
 */
import { useState } from 'react';
import AdminRequest from '../../models/AdminRequest.js';
import './TablaContenido.css';

/* Formulario vacío por defecto */
const FORM_VACIO = {
  titulo: '',
  categoria: '',
  anio: new Date().getFullYear(),
  descripcion: '',
  tags: '',        // se ingresa como string separado por comas
  imagen: '',
  destacado: false,
};

export default function TablaContenido({ contenido, setContenido, adminNombre, onNuevaRequest }) {
  // ID del ítem en edición (null = modo creación)
  const [editandoId, setEditandoId] = useState(null);
  // Datos del formulario
  const [form, setForm] = useState(FORM_VACIO);
  // ID del ítem con confirmación de borrado pendiente
  const [confirmandoBorradoId, setConfirmandoBorradoId] = useState(null);
  // Mostrar/ocultar el formulario
  const [mostrarForm, setMostrarForm] = useState(false);

  /* --- Helpers de formulario --- */

  function handleCampoChange(e) {
    const { name, value, type, checked } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value,
    }));
  }

  function resetForm() {
    setForm(FORM_VACIO);
    setEditandoId(null);
    setMostrarForm(false);
  }

  /* --- Handlers CRUD --- */

  function handleCrear(e) {
    e.preventDefault();

    // Calcular nuevo ID: max existente + 1
    const nuevoId =
      contenido.length > 0
        ? Math.max(...contenido.map((c) => c.id)) + 1
        : 1;

    const nuevo = {
      ...form,
      id: nuevoId,
      anio: parseInt(form.anio, 10),
      // Convertir el string de tags a array
      tags: form.tags
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean),
      likes: 0,
      destacado: Boolean(form.destacado),
    };

    // POO obligatorio: instanciar y loguear la petición
    const req = new AdminRequest('CREATE', 'contenido', nuevo, adminNombre).log();
    onNuevaRequest(req);

    // Actualizar estado de forma inmutable
    setContenido((prev) => [...prev, nuevo]);
    resetForm();
  }

  function handleCargarEdicion(item) {
    setEditandoId(item.id);
    setForm({
      titulo: item.titulo,
      categoria: item.categoria,
      anio: item.anio,
      descripcion: item.descripcion,
      tags: Array.isArray(item.tags) ? item.tags.join(', ') : item.tags,
      imagen: item.imagen,
      destacado: Boolean(item.destacado),
    });
    setMostrarForm(true);
    // Scroll al formulario
    setTimeout(() => {
      document.getElementById('form-contenido')?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }, 50);
  }

  function handleEditar(e) {
    e.preventDefault();

    const actualizado = {
      ...contenido.find((c) => c.id === editandoId),
      ...form,
      anio: parseInt(form.anio, 10),
      tags: form.tags
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean),
      destacado: Boolean(form.destacado),
    };

    // POO obligatorio
    const req = new AdminRequest('UPDATE', 'contenido', actualizado, adminNombre).log();
    onNuevaRequest(req);

    // Actualizar con .map() inmutable
    setContenido((prev) =>
      prev.map((c) => (c.id === editandoId ? actualizado : c))
    );
    resetForm();
  }

  function handleSolicitarBorrado(id) {
    setConfirmandoBorradoId(id);
  }

  function handleCancelarBorrado() {
    setConfirmandoBorradoId(null);
  }

  function handleBorrar(id) {
    const item = contenido.find((c) => c.id === id);

    // POO obligatorio
    const req = new AdminRequest('DELETE', 'contenido', item, adminNombre).log();
    onNuevaRequest(req);

    // Actualizar con .filter() inmutable
    setContenido((prev) => prev.filter((c) => c.id !== id));
    setConfirmandoBorradoId(null);

    // Si se borraba el ítem en edición, limpiar el formulario
    if (editandoId === id) resetForm();
  }

  const modoEdicion = editandoId !== null;

  return (
    <div className="tc-wrapper">
      {/* Botón para abrir el formulario de nuevo ítem */}
      {!mostrarForm && (
        <div className="tc-toolbar">
          <button
            className="btn-brutal btn-brutal--accent"
            onClick={() => { resetForm(); setMostrarForm(true); }}
          >
            + AGREGAR CONTENIDO
          </button>
        </div>
      )}

      {/* Formulario de creación / edición */}
      {mostrarForm && (
        <form
          id="form-contenido"
          className="tc-form"
          onSubmit={modoEdicion ? handleEditar : handleCrear}
          noValidate
        >
          <div className="tc-form-header">
            <span className="tc-form-titulo">
              {modoEdicion ? `EDITANDO: ${form.titulo || '—'}` : 'NUEVO CONTENIDO'}
            </span>
            <button
              type="button"
              className="btn-brutal tc-form-cerrar"
              onClick={resetForm}
            >
              ✕ CANCELAR
            </button>
          </div>

          <div className="tc-form-grid">
            {/* Título */}
            <div className="tc-campo tc-campo--full">
              <label className="tc-label" htmlFor="fc-titulo">TÍTULO</label>
              <input
                id="fc-titulo"
                className="tc-input"
                type="text"
                name="titulo"
                value={form.titulo}
                onChange={handleCampoChange}
                placeholder="Título del proyecto"
                required
              />
            </div>

            {/* Categoría */}
            <div className="tc-campo">
              <label className="tc-label" htmlFor="fc-categoria">CATEGORÍA</label>
              <input
                id="fc-categoria"
                className="tc-input"
                type="text"
                name="categoria"
                value={form.categoria}
                onChange={handleCampoChange}
                placeholder="Ej: Desarrollo Web"
                required
              />
            </div>

            {/* Año */}
            <div className="tc-campo">
              <label className="tc-label" htmlFor="fc-anio">AÑO</label>
              <input
                id="fc-anio"
                className="tc-input"
                type="number"
                name="anio"
                value={form.anio}
                onChange={handleCampoChange}
                min="2000"
                max="2099"
                required
              />
            </div>

            {/* Descripción */}
            <div className="tc-campo tc-campo--full">
              <label className="tc-label" htmlFor="fc-descripcion">DESCRIPCIÓN</label>
              <textarea
                id="fc-descripcion"
                className="tc-input tc-textarea"
                name="descripcion"
                value={form.descripcion}
                onChange={handleCampoChange}
                placeholder="Descripción breve del proyecto..."
                rows={3}
                required
              />
            </div>

            {/* Tags */}
            <div className="tc-campo tc-campo--full">
              <label className="tc-label" htmlFor="fc-tags">
                TAGS <span className="tc-label-hint">(separados por coma)</span>
              </label>
              <input
                id="fc-tags"
                className="tc-input"
                type="text"
                name="tags"
                value={form.tags}
                onChange={handleCampoChange}
                placeholder="React, CSS, API REST"
              />
            </div>

            {/* Imagen */}
            <div className="tc-campo tc-campo--full">
              <label className="tc-label" htmlFor="fc-imagen">URL DE IMAGEN</label>
              <input
                id="fc-imagen"
                className="tc-input"
                type="url"
                name="imagen"
                value={form.imagen}
                onChange={handleCampoChange}
                placeholder="https://..."
              />
            </div>

            {/* Destacado */}
            <div className="tc-campo tc-campo--check">
              <label className="tc-label-check">
                <input
                  className="tc-checkbox"
                  type="checkbox"
                  name="destacado"
                  checked={form.destacado}
                  onChange={handleCampoChange}
                />
                <span>DESTACADO</span>
              </label>
            </div>
          </div>

          <div className="tc-form-actions">
            <button type="submit" className="btn-brutal btn-brutal--accent">
              {modoEdicion ? '✓ GUARDAR CAMBIOS' : '+ CREAR CONTENIDO'}
            </button>
            <button type="button" className="btn-brutal" onClick={resetForm}>
              CANCELAR
            </button>
          </div>
        </form>
      )}

      {/* Tabla de contenido */}
      <div className="tabla-scroll">
        <table className="tabla-brutal">
          <thead>
            <tr>
              <th>ID</th>
              <th>TÍTULO</th>
              <th>CATEGORÍA</th>
              <th>AÑO</th>
              <th>TAGS</th>
              <th>DEST.</th>
              <th>LIKES</th>
              <th>ACCIONES</th>
            </tr>
          </thead>
          <tbody>
            {contenido.length === 0 && (
              <tr>
                <td colSpan={8} className="tc-vacio">
                  No hay contenido registrado.
                </td>
              </tr>
            )}
            {contenido.map((item) => (
              <tr
                key={item.id}
                className={editandoId === item.id ? 'tc-fila-activa' : ''}
              >
                <td className="tabla-mono tc-id">#{item.id}</td>
                <td>
                  <span className="tc-titulo-celda">{item.titulo}</span>
                  <span className="tc-desc-celda">{item.descripcion?.slice(0, 60)}…</span>
                </td>
                <td>
                  <span className="tag-brutal">{item.categoria}</span>
                </td>
                <td className="tabla-mono">{item.anio}</td>
                <td>
                  <div className="tc-tags">
                    {(Array.isArray(item.tags) ? item.tags : []).slice(0, 3).map((t) => (
                      <span key={t} className="tag-brutal tc-tag-item">{t}</span>
                    ))}
                  </div>
                </td>
                <td className="tabla-mono">
                  {item.destacado ? (
                    <span className="tabla-badge tabla-badge--admin">★</span>
                  ) : (
                    <span className="tabla-badge tabla-badge--no">—</span>
                  )}
                </td>
                <td className="tabla-mono tabla-num">{item.likes}</td>

                {/* Celda de acciones */}
                <td className="tc-acciones">
                  {confirmandoBorradoId === item.id ? (
                    /* Confirmación de borrado inline */
                    <div className="tc-confirm">
                      <span className="tc-confirm-texto">¿Borrar?</span>
                      <button
                        className="btn-brutal btn-brutal--danger tc-btn-sm"
                        onClick={() => handleBorrar(item.id)}
                      >
                        SÍ
                      </button>
                      <button
                        className="btn-brutal tc-btn-sm"
                        onClick={handleCancelarBorrado}
                      >
                        NO
                      </button>
                    </div>
                  ) : (
                    <>
                      <button
                        className="btn-brutal tc-btn-sm"
                        onClick={() => handleCargarEdicion(item)}
                        title="Editar ítem"
                      >
                        EDITAR
                      </button>
                      <button
                        className="btn-brutal btn-brutal--danger tc-btn-sm"
                        onClick={() => handleSolicitarBorrado(item.id)}
                        title="Eliminar ítem"
                      >
                        BORRAR
                      </button>
                    </>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// src/components/admin/TablaContenido.vue
<script setup>
import './TablaContenido.css'
import { ref, reactive } from 'vue'
import AdminRequest from '../../models/AdminRequest.js'

// Props y emits
const props = defineProps({
  contenido: {
    type: Array,
    required: true
  },
  autorAdmin: {
    type: String,
    required: true
  }
})

// El padre escucha estos eventos para mantener su ref actualizado
// y para agregar cada AdminRequest al historial de auditoría
const emit = defineEmits(['crear', 'editar', 'borrar', 'auditoria'])

// ─── Estado del formulario de creación / edición ───────────────────────────

const FORM_VACIO = {
  titulo: '',
  categoria: '',
  anio: new Date().getFullYear(),
  descripcion: '',
  tags: '',          // string separado por comas; se parseará al emitir
  imagen: '',
  destacado: false
}

const mostrarFormCrear = ref(false)
const formCrear = reactive({ ...FORM_VACIO })

// Para edición guardamos el id original
const editandoId = ref(null)
const formEditar = reactive({ ...FORM_VACIO })

// Confirmación de borrado inline (no window.confirm)
const confirmandoBorrarId = ref(null)

// ─── Helpers ──────────────────────────────────────────────────────────────

function parseTags(tagsStr) {
  return tagsStr
    .split(',')
    .map((t) => t.trim())
    .filter(Boolean)
}

function idNuevo(lista) {
  if (lista.length === 0) return 1
  return Math.max(...lista.map((i) => i.id)) + 1
}

// ─── Crear ────────────────────────────────────────────────────────────────

function abrirFormCrear() {
  Object.assign(formCrear, FORM_VACIO)
  mostrarFormCrear.value = true
  editandoId.value = null
  confirmandoBorrarId.value = null
}

function cancelarCrear() {
  mostrarFormCrear.value = false
}

function submitCrear() {
  const nuevoItem = {
    id: idNuevo(props.contenido),
    titulo: formCrear.titulo.trim(),
    categoria: formCrear.categoria.trim(),
    anio: Number(formCrear.anio),
    descripcion: formCrear.descripcion.trim(),
    tags: parseTags(formCrear.tags),
    imagen: formCrear.imagen.trim() || `https://picsum.photos/seed/${Date.now()}/800/600`,
    destacado: formCrear.destacado,
    likes: 0
  }

  /*
   * POO OBLIGATORIO: se instancia AdminRequest ante cada operación.
   * .log() es encadenable y devuelve la misma instancia, que queda
   * disponible para el registro de auditoría.
   */
  const req = new AdminRequest('CREATE', 'contenido', nuevoItem, props.autorAdmin).log()

  emit('crear', nuevoItem)
  emit('auditoria', req)
  mostrarFormCrear.value = false
}

// ─── Editar ───────────────────────────────────────────────────────────────

function abrirEditar(item) {
  editandoId.value = item.id
  Object.assign(formEditar, {
    titulo: item.titulo,
    categoria: item.categoria,
    anio: item.anio,
    descripcion: item.descripcion,
    tags: item.tags.join(', '),
    imagen: item.imagen,
    destacado: item.destacado
  })
  mostrarFormCrear.value = false
  confirmandoBorrarId.value = null
}

function cancelarEditar() {
  editandoId.value = null
}

function submitEditar(item) {
  const actualizado = {
    ...item,
    titulo: formEditar.titulo.trim(),
    categoria: formEditar.categoria.trim(),
    anio: Number(formEditar.anio),
    descripcion: formEditar.descripcion.trim(),
    tags: parseTags(formEditar.tags),
    imagen: formEditar.imagen.trim(),
    destacado: formEditar.destacado
  }

  const req = new AdminRequest('UPDATE', 'contenido', actualizado, props.autorAdmin).log()

  emit('editar', actualizado)
  emit('auditoria', req)
  editandoId.value = null
}

// ─── Borrar ───────────────────────────────────────────────────────────────

function pedirConfirmacion(id) {
  confirmandoBorrarId.value = id
  editandoId.value = null
}

function cancelarBorrar() {
  confirmandoBorrarId.value = null
}

function confirmarBorrar(item) {
  const req = new AdminRequest('DELETE', 'contenido', { id: item.id, titulo: item.titulo }, props.autorAdmin).log()

  emit('borrar', item.id)
  emit('auditoria', req)
  confirmandoBorrarId.value = null
}
</script>

<template>
  <div class="tc-wrapper">
    <!-- Botón para abrir el formulario de nuevo contenido -->
    <div class="tc-acciones-top">
      <button
        v-if="!mostrarFormCrear"
        class="btn-brutal btn-brutal--accent tc-btn-nuevo"
        @click="abrirFormCrear"
      >
        + Agregar contenido
      </button>
    </div>

    <!-- ── Formulario de creación ─────────────────────────── -->
    <div
      v-if="mostrarFormCrear"
      class="tc-form-panel"
    >
      <div class="tc-form-cabecera">
        <span class="tc-form-titulo">Nuevo contenido</span>
        <button
          class="btn-brutal tc-btn-cancelar"
          @click="cancelarCrear"
        >
          ✕ Cancelar
        </button>
      </div>

      <form
        class="tc-form"
        @submit.prevent="submitCrear"
      >
        <div class="tc-form-fila tc-form-fila--2">
          <div class="tc-form-campo">
            <label class="tc-form-label">Título *</label>
            <input
              v-model="formCrear.titulo"
              class="tc-form-input"
              type="text"
              required
              placeholder="Ej: Mi proyecto"
            >
          </div>
          <div class="tc-form-campo">
            <label class="tc-form-label">Categoría *</label>
            <input
              v-model="formCrear.categoria"
              class="tc-form-input"
              type="text"
              required
              placeholder="Ej: Desarrollo Web"
            >
          </div>
        </div>

        <div class="tc-form-fila tc-form-fila--2">
          <div class="tc-form-campo">
            <label class="tc-form-label">Año *</label>
            <input
              v-model="formCrear.anio"
              class="tc-form-input"
              type="number"
              required
              min="2000"
              max="2099"
            >
          </div>
          <div class="tc-form-campo">
            <label class="tc-form-label">Tags (separados por coma)</label>
            <input
              v-model="formCrear.tags"
              class="tc-form-input"
              type="text"
              placeholder="Ej: Vue, CSS, Firebase"
            >
          </div>
        </div>

        <div class="tc-form-campo">
          <label class="tc-form-label">Descripción *</label>
          <textarea
            v-model="formCrear.descripcion"
            class="tc-form-input tc-form-textarea"
            required
            rows="3"
            placeholder="Descripción del proyecto..."
          />
        </div>

        <div class="tc-form-campo">
          <label class="tc-form-label">URL de imagen</label>
          <input
            v-model="formCrear.imagen"
            class="tc-form-input"
            type="url"
            placeholder="https://..."
          >
        </div>

        <div class="tc-form-check">
          <label class="tc-form-check-label">
            <input
              v-model="formCrear.destacado"
              type="checkbox"
              class="tc-form-checkbox"
            >
            Marcar como destacado
          </label>
        </div>

        <div class="tc-form-submit">
          <button
            type="submit"
            class="btn-brutal btn-brutal--accent"
          >
            Crear contenido
          </button>
          <button
            type="button"
            class="btn-brutal"
            @click="cancelarCrear"
          >
            Cancelar
          </button>
        </div>
      </form>
    </div>

    <!-- ── Tabla de contenido ─────────────────────────────── -->
    <div class="tabla-overflow">
      <table class="tabla-brutal tc-tabla">
        <thead>
          <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Categoría</th>
            <th>Año</th>
            <th>Tags</th>
            <th>Dest.</th>
            <th>Likes</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <template
            v-for="item in props.contenido"
            :key="item.id"
          >
            <!-- Fila normal -->
            <tr
              v-if="editandoId !== item.id"
              :class="{ 'tc-fila--destacado': item.destacado }"
            >
              <td class="tc-celda--id">
                {{ item.id }}
              </td>
              <td class="tc-celda--titulo">
                {{ item.titulo }}
              </td>
              <td class="tc-celda--cat">
                <span class="tag-brutal">{{ item.categoria }}</span>
              </td>
              <td class="tc-celda--anio">
                {{ item.anio }}
              </td>
              <td class="tc-celda--tags">
                <span
                  v-for="tag in item.tags"
                  :key="tag"
                  class="tag-brutal tc-tag"
                >{{ tag }}</span>
              </td>
              <td class="tc-celda--bool">
                <span :class="item.destacado ? 'tc-star--si' : 'tc-star--no'">
                  {{ item.destacado ? '★' : '☆' }}
                </span>
              </td>
              <td class="tc-celda--num">
                {{ item.likes }}
              </td>
              <td class="tc-celda--acciones">
                <!-- Confirmar borrado inline -->
                <div
                  v-if="confirmandoBorrarId === item.id"
                  class="tc-confirmar-borrar"
                >
                  <span class="tc-confirmar-texto">¿Borrar?</span>
                  <button
                    class="btn-brutal btn-brutal--danger tc-btn-accion"
                    @click="confirmarBorrar(item)"
                  >
                    Sí
                  </button>
                  <button
                    class="btn-brutal tc-btn-accion"
                    @click="cancelarBorrar"
                  >
                    No
                  </button>
                </div>
                <div
                  v-else
                  class="tc-acciones-fila"
                >
                  <button
                    class="btn-brutal tc-btn-accion"
                    @click="abrirEditar(item)"
                  >
                    Editar
                  </button>
                  <button
                    class="btn-brutal btn-brutal--danger tc-btn-accion"
                    @click="pedirConfirmacion(item.id)"
                  >
                    Borrar
                  </button>
                </div>
              </td>
            </tr>

            <!-- Fila en modo edición (inline) -->
            <tr
              v-else
              class="tc-fila--editando"
            >
              <td
                colspan="8"
                class="tc-celda--form-editar"
              >
                <div class="tc-form-panel tc-form-panel--inline">
                  <div class="tc-form-cabecera">
                    <span class="tc-form-titulo">Editando: {{ item.titulo }}</span>
                    <button
                      class="btn-brutal tc-btn-cancelar"
                      @click="cancelarEditar"
                    >
                      ✕ Cancelar
                    </button>
                  </div>
                  <form
                    class="tc-form"
                    @submit.prevent="submitEditar(item)"
                  >
                    <div class="tc-form-fila tc-form-fila--2">
                      <div class="tc-form-campo">
                        <label class="tc-form-label">Título *</label>
                        <input
                          v-model="formEditar.titulo"
                          class="tc-form-input"
                          type="text"
                          required
                        >
                      </div>
                      <div class="tc-form-campo">
                        <label class="tc-form-label">Categoría *</label>
                        <input
                          v-model="formEditar.categoria"
                          class="tc-form-input"
                          type="text"
                          required
                        >
                      </div>
                    </div>
                    <div class="tc-form-fila tc-form-fila--2">
                      <div class="tc-form-campo">
                        <label class="tc-form-label">Año *</label>
                        <input
                          v-model="formEditar.anio"
                          class="tc-form-input"
                          type="number"
                          required
                          min="2000"
                          max="2099"
                        >
                      </div>
                      <div class="tc-form-campo">
                        <label class="tc-form-label">Tags (coma)</label>
                        <input
                          v-model="formEditar.tags"
                          class="tc-form-input"
                          type="text"
                        >
                      </div>
                    </div>
                    <div class="tc-form-campo">
                      <label class="tc-form-label">Descripción *</label>
                      <textarea
                        v-model="formEditar.descripcion"
                        class="tc-form-input tc-form-textarea"
                        required
                        rows="2"
                      />
                    </div>
                    <div class="tc-form-campo">
                      <label class="tc-form-label">URL imagen</label>
                      <input
                        v-model="formEditar.imagen"
                        class="tc-form-input"
                        type="url"
                      >
                    </div>
                    <div class="tc-form-check">
                      <label class="tc-form-check-label">
                        <input
                          v-model="formEditar.destacado"
                          type="checkbox"
                          class="tc-form-checkbox"
                        >
                        Destacado
                      </label>
                    </div>
                    <div class="tc-form-submit">
                      <button
                        type="submit"
                        class="btn-brutal btn-brutal--accent"
                      >
                        Guardar cambios
                      </button>
                      <button
                        type="button"
                        class="btn-brutal"
                        @click="cancelarEditar"
                      >
                        Cancelar
                      </button>
                    </div>
                  </form>
                </div>
              </td>
            </tr>
          </template>
        </tbody>
      </table>
    </div>

    <p
      v-if="props.contenido.length === 0"
      class="tabla-vacia"
    >
      No hay contenido registrado.
    </p>
  </div>
</template>
