// src/components/admin/TablaUsuarios.vue
<script setup>
import './TablaUsuarios.css'

// La tabla de usuarios es solo lectura: recibe el array desde el padre
const props = defineProps({
  usuarios: {
    type: Array,
    required: true
  }
})

/**
 * Formatea una fecha ISO en formato local legible.
 * @param {string} fechaISO
 * @returns {string}
 */
function formatFecha(fechaISO) {
  if (!fechaISO) return '—'
  const [anio, mes, dia] = fechaISO.split('-')
  return `${dia}/${mes}/${anio}`
}
</script>

<template>
  <div class="tabla-wrapper">
    <div class="tabla-overflow">
      <table class="tabla-brutal">
        <thead>
          <tr>
            <th>Usuario</th>
            <th>Email</th>
            <th>Admin</th>
            <th>Suscrito</th>
            <th>Registro</th>
            <th>Likes</th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="usuario in props.usuarios"
            :key="usuario.name"
            :class="{ 'tabla-fila--admin': usuario.isAdmin }"
          >
            <td class="tabla-celda--nombre">
              <span class="tabla-nombre">{{ usuario.name }}</span>
              <span
                v-if="usuario.isAdmin"
                class="tabla-badge tabla-badge--admin"
              >admin</span>
            </td>
            <td class="tabla-celda--email">
              {{ usuario.email }}
            </td>
            <td class="tabla-celda--bool">
              <span
                class="tabla-status"
                :class="usuario.isAdmin ? 'tabla-status--si' : 'tabla-status--no'"
              >
                {{ usuario.isAdmin ? 'SÍ' : 'NO' }}
              </span>
            </td>
            <td class="tabla-celda--bool">
              <span
                class="tabla-status"
                :class="usuario.isSubscribed ? 'tabla-status--si' : 'tabla-status--no'"
              >
                {{ usuario.isSubscribed ? 'SÍ' : 'NO' }}
              </span>
            </td>
            <td class="tabla-celda--fecha">
              {{ formatFecha(usuario.registerDate) }}
            </td>
            <td class="tabla-celda--num">
              {{ usuario.likedPostIDs?.length ?? 0 }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <p
      v-if="props.usuarios.length === 0"
      class="tabla-vacia"
    >
      No hay usuarios registrados.
    </p>
  </div>
</template>

// src/components/admin/TablaUsuarios.jsx
/**
 * TablaUsuarios — tabla de solo lectura con todos los usuarios del sistema.
 * Muestra: nombre, email, rol admin, suscripción, fecha de registro, cantidad de likes.
 */
import './TablaUsuarios.css';

export default function TablaUsuarios({ usuarios }) {
  return (
    <div className="tabla-scroll">
      <table className="tabla-brutal">
        <thead>
          <tr>
            <th>USUARIO</th>
            <th>EMAIL</th>
            <th>ADMIN</th>
            <th>SUSCRIPTO</th>
            <th>REGISTRO</th>
            <th>LIKES</th>
          </tr>
        </thead>
        <tbody>
          {usuarios.map((u) => (
            <tr key={u.name}>
              <td>
                <span className="tabla-nombre">{u.name}</span>
              </td>
              <td>{u.email}</td>
              <td>
                {u.isAdmin ? (
                  <span className="tabla-badge tabla-badge--admin">SÍ</span>
                ) : (
                  <span className="tabla-badge tabla-badge--no">NO</span>
                )}
              </td>
              <td>
                {u.isSubscribed ? (
                  <span className="tabla-badge tabla-badge--ok">SÍ</span>
                ) : (
                  <span className="tabla-badge tabla-badge--no">NO</span>
                )}
              </td>
              <td className="tabla-mono">{u.registerDate}</td>
              <td className="tabla-mono tabla-num">{u.likedPostIDs.length}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
