// src/pages/Admin.jsx
/**
 * Admin.jsx — página del panel de administración.
 *
 * Flujo:
 *  1. Login simulado → fetch /usuarios.json → validar credenciales
 *  2a. Sin acceso admin → pantalla de bloqueo <AccesoRestringido>
 *  2b. Admin confirmado → panel con pestañas: Usuarios | Contenido
 *  3. Panel: TablaUsuarios (solo lectura) + TablaContenido (CRUD completo)
 *  4. Registro de auditoría de todas las AdminRequest generadas
 */
import { useState, useEffect } from 'react';
import LoginForm from '../components/admin/LoginForm.jsx';
import AccesoRestringido from '../components/admin/AccesoRestringido.jsx';
import TablaUsuarios from '../components/admin/TablaUsuarios.jsx';
import TablaContenido from '../components/admin/TablaContenido.jsx';
import RegistroAuditoria from '../components/admin/RegistroAuditoria.jsx';
import './Admin.css';

// Estados posibles de autenticación
const AUTH = {
  PENDIENTE: 'PENDIENTE',     // no ha intentado login aún
  BLOQUEADO: 'BLOQUEADO',     // credenciales ok pero sin isAdmin
  AUTENTICADO: 'AUTENTICADO', // admin confirmado
};

// Pestañas del panel
const PESTANAS = {
  USUARIOS: 'USUARIOS',
  CONTENIDO: 'CONTENIDO',
};

export default function Admin() {
  // Estado de autenticación y usuario logueado
  const [authEstado, setAuthEstado] = useState(AUTH.PENDIENTE);
  const [usuarioLogueado, setUsuarioLogueado] = useState(null);

  // Datos cargados desde JSON
  const [usuarios, setUsuarios] = useState([]);
  const [contenido, setContenido] = useState([]);

  // Pestaña activa del panel
  const [pestanaActiva, setPestanaActiva] = useState(PESTANAS.USUARIOS);

  // Historial de AdminRequests para el registro de auditoría
  const [historial, setHistorial] = useState([]);

  // Precargar ambos JSON una sola vez al montar el componente
  useEffect(() => {
    async function precargarDatos() {
      try {
        const [resUsers, resContent] = await Promise.all([
          fetch('/usuarios.json'),
          fetch('/contenido.json'),
        ]);
        const [u, c] = await Promise.all([resUsers.json(), resContent.json()]);
        setUsuarios(u);
        setContenido(c);
      } catch (err) {
        console.error('Error precargando datos:', err);
      }
    }
    precargarDatos();
  }, []);

  /* --- Handlers de autenticación --- */

  function handleLoginExitoso(usuario) {
    setUsuarioLogueado(usuario);
    setAuthEstado(AUTH.AUTENTICADO);
  }

  function handleLoginBloqueado(usuario) {
    setUsuarioLogueado(usuario);
    setAuthEstado(AUTH.BLOQUEADO);
  }

  function handleReintentar() {
    setAuthEstado(AUTH.PENDIENTE);
    setUsuarioLogueado(null);
  }

  function handleLogout() {
    setAuthEstado(AUTH.PENDIENTE);
    setUsuarioLogueado(null);
    setPestanaActiva(PESTANAS.USUARIOS);
    setHistorial([]);
  }

  /* --- Handler para agregar una nueva petición al historial --- */

  function handleNuevaRequest(req) {
    setHistorial((prev) => [...prev, req]);
  }

  /* ── Renderizado condicional según estado de auth ── */

  if (authEstado === AUTH.PENDIENTE) {
    return (
      <LoginForm
        onLoginExitoso={handleLoginExitoso}
        onLoginBloqueado={handleLoginBloqueado}
      />
    );
  }

  if (authEstado === AUTH.BLOQUEADO) {
    return (
      <AccesoRestringido
        usuario={usuarioLogueado}
        onReintentar={handleReintentar}
      />
    );
  }

  /* ── Panel admin ── */

  return (
    <div className="admin-panel">
      <div className="container">

        {/* Encabezado del panel */}
        <header className="admin-encabezado">
          <div className="admin-encabezado-izq">
            <span className="admin-stamp">PANEL ADMIN</span>
            <h1 className="admin-titulo">CONTROL<br />TOTAL</h1>
          </div>
          <div className="admin-encabezado-der">
            <div className="admin-sesion">
              <span className="admin-sesion-label">SESIÓN ACTIVA</span>
              <span className="admin-sesion-usuario">{usuarioLogueado?.name}</span>
              <span className="admin-sesion-email">{usuarioLogueado?.email}</span>
            </div>
            <button
              className="btn-brutal btn-brutal--danger admin-logout"
              onClick={handleLogout}
            >
              CERRAR SESIÓN
            </button>
          </div>
        </header>

        {/* Pestañas tipo brutalismo */}
        <nav className="admin-tabs" role="tablist" aria-label="Secciones del panel">
          <button
            className={`admin-tab ${pestanaActiva === PESTANAS.USUARIOS ? 'admin-tab--activa' : ''}`}
            role="tab"
            aria-selected={pestanaActiva === PESTANAS.USUARIOS}
            onClick={() => setPestanaActiva(PESTANAS.USUARIOS)}
          >
            USUARIOS
            <span className="admin-tab-count">{usuarios.length}</span>
          </button>
          <button
            className={`admin-tab ${pestanaActiva === PESTANAS.CONTENIDO ? 'admin-tab--activa' : ''}`}
            role="tab"
            aria-selected={pestanaActiva === PESTANAS.CONTENIDO}
            onClick={() => setPestanaActiva(PESTANAS.CONTENIDO)}
          >
            CONTENIDO
            <span className="admin-tab-count">{contenido.length}</span>
          </button>
        </nav>

        {/* Contenido de la pestaña activa */}
        <section className="admin-seccion" aria-label={`Tabla de ${pestanaActiva}`}>
          <div className="admin-seccion-header">
            <h2 className="admin-seccion-titulo">{pestanaActiva}</h2>
            {pestanaActiva === PESTANAS.USUARIOS && (
              <span className="tag-brutal">SOLO LECTURA</span>
            )}
            {pestanaActiva === PESTANAS.CONTENIDO && (
              <span className="tag-brutal">CRUD COMPLETO</span>
            )}
          </div>

          {pestanaActiva === PESTANAS.USUARIOS && (
            <TablaUsuarios usuarios={usuarios} />
          )}

          {pestanaActiva === PESTANAS.CONTENIDO && (
            <TablaContenido
              contenido={contenido}
              setContenido={setContenido}
              adminNombre={usuarioLogueado?.name}
              onNuevaRequest={handleNuevaRequest}
            />
          )}
        </section>

        {/* Registro de auditoría: siempre visible en el panel */}
        <section className="admin-auditoria" aria-label="Registro de auditoría">
          <div className="admin-seccion-header">
            <h2 className="admin-seccion-titulo">AUDITORÍA</h2>
            <span className="tag-brutal">AdminRequest · POO</span>
          </div>
          <RegistroAuditoria historial={historial} />
        </section>

      </div>
    </div>
  );
}

// src/pages/Admin.vue
<script setup>
import './Admin.css'
import { ref } from 'vue'

import LoginForm from '../components/admin/LoginForm.vue'
import PantallaBloqueo from '../components/admin/PantallaBloqueo.vue'
import TablaUsuarios from '../components/admin/TablaUsuarios.vue'
import TablaContenido from '../components/admin/TablaContenido.vue'
import RegistroAuditoria from '../components/admin/RegistroAuditoria.vue'

// ─── Estado de sesión ──────────────────────────────────────────────────────

/**
 * Estado de la pantalla actual:
 *   'login'      → formulario de autenticación
 *   'bloqueado'  → usuario sin isAdmin (pantalla negra de acceso restringido)
 *   'panel'      → admin autenticado, panel completo
 */
const pantalla = ref('login')

/** Usuario autenticado o usuario sin permisos (para mostrar en PantallaBloqueo). */
const usuarioActual = ref(null)

// ─── Datos del panel ───────────────────────────────────────────────────────

/**
 * Ref reactivo para los usuarios: cargado desde /usuarios.json al entrar al panel.
 * Al ser un Proxy de Vue (ref/reactive), cualquier mutación directa del array
 * desencadena re-render automático, sin necesidad de setState como en React.
 */
const usuarios = ref([])

/**
 * Ref reactivo para el contenido: cargado desde /contenido.json al entrar al panel.
 * La reactividad por Proxy de Vue permite hacer contenido.value.push(item) o
 * .splice() directamente y la UI se actualiza sola — a diferencia de React donde
 * habría que llamar setContenido([...prev, item]) para disparar un nuevo render.
 */
const contenido = ref([])

const cargandoPanel = ref(false)
const errorPanel = ref('')

// ─── Pestañas ─────────────────────────────────────────────────────────────

/** Pestaña activa: 'usuarios' | 'contenido' */
const tabActiva = ref('usuarios')

// ─── Historial de auditoría (AdminRequest[]) ───────────────────────────────

const historialAuditoria = ref([])

// ─── Handlers de autenticación ────────────────────────────────────────────

/**
 * LoginForm emite 'login-exitoso' con el objeto usuario admin.
 * Cargamos usuarios y contenido antes de mostrar el panel.
 */
async function onLoginExitoso(usuario) {
  usuarioActual.value = usuario
  cargandoPanel.value = true
  errorPanel.value = ''

  try {
    const [resUsuarios, resContenido] = await Promise.all([
      fetch('/usuarios.json'),
      fetch('/contenido.json')
    ])

    if (!resUsuarios.ok || !resContenido.ok) {
      throw new Error('No se pudieron cargar los datos del panel.')
    }

    usuarios.value = await resUsuarios.json()
    contenido.value = await resContenido.json()

    pantalla.value = 'panel'
  } catch (e) {
    errorPanel.value = e.message
  } finally {
    cargandoPanel.value = false
  }
}

/**
 * LoginForm emite 'acceso-restringido' con el usuario sin permisos.
 * Mostramos la pantalla de bloqueo dramática.
 */
function onAccesoRestringido(usuario) {
  usuarioActual.value = usuario
  pantalla.value = 'bloqueado'
}

/**
 * PantallaBloqueo emite 'reintentar': volvemos al formulario de login.
 */
function onReintentar() {
  usuarioActual.value = null
  pantalla.value = 'login'
}

/**
 * Cierre de sesión: resetea todo el estado y vuelve al login.
 */
function logout() {
  usuarioActual.value = null
  usuarios.value = []
  contenido.value = []
  historialAuditoria.value = []
  tabActiva.value = 'usuarios'
  pantalla.value = 'login'
}

// ─── Handlers CRUD de contenido ───────────────────────────────────────────

/**
 * TablaContenido emite 'crear' con el nuevo objeto.
 * Mutación directa del ref — Vue detecta el cambio por Proxy y re-renderiza.
 */
function onCrearContenido(nuevoItem) {
  contenido.value.push(nuevoItem)
}

/**
 * TablaContenido emite 'editar' con el objeto actualizado.
 * Reemplazamos el ítem en el array por índice.
 */
function onEditarContenido(itemActualizado) {
  const idx = contenido.value.findIndex((c) => c.id === itemActualizado.id)
  if (idx !== -1) {
    // Asignación directa al índice: Vue 3 la detecta gracias al Proxy del array
    contenido.value[idx] = itemActualizado
  }
}

/**
 * TablaContenido emite 'borrar' con el id a eliminar.
 */
function onBorrarContenido(id) {
  const idx = contenido.value.findIndex((c) => c.id === id)
  if (idx !== -1) {
    contenido.value.splice(idx, 1)
  }
}

/**
 * TablaContenido emite 'auditoria' con la instancia de AdminRequest ya logueada.
 * La agregamos al historial que renderiza RegistroAuditoria.
 */
function onAuditoria(req) {
  historialAuditoria.value.push(req)
}
</script>

<template>
  <!-- ── Pantalla de login ───────────────────────────────────── -->
  <div v-if="pantalla === 'login'">
    <LoginForm
      @login-exitoso="onLoginExitoso"
      @acceso-restringido="onAccesoRestringido"
    />

    <!-- Error al cargar los datos del panel (tras login válido) -->
    <div
      v-if="errorPanel"
      class="container admin-error-panel"
      role="alert"
    >
      Error al cargar datos del panel: {{ errorPanel }}
    </div>

    <!-- Indicador de carga del panel -->
    <div
      v-if="cargandoPanel"
      class="container admin-cargando"
    >
      <span class="admin-cargando-texto">Cargando panel...</span>
    </div>
  </div>

  <!-- ── Pantalla de bloqueo ────────────────────────────────── -->
  <div v-else-if="pantalla === 'bloqueado'">
    <PantallaBloqueo
      :usuario="usuarioActual"
      @reintentar="onReintentar"
    />
  </div>

  <!-- ── Panel de administración ───────────────────────────── -->
  <div
    v-else-if="pantalla === 'panel'"
    class="admin-panel"
  >
    <div class="container">
      <!-- Encabezado con info de sesión y logout -->
      <header class="admin-encabezado">
        <div class="admin-encabezado-izq">
          <span class="admin-stamp">Sistema de gestión — sesión activa</span>
          <h1 class="admin-titulo">
            Panel<br>Admin
          </h1>
        </div>

        <div class="admin-encabezado-der">
          <div class="admin-sesion">
            <span class="admin-sesion-label">Conectado como</span>
            <span class="admin-sesion-usuario">{{ usuarioActual?.name }}</span>
            <span class="admin-sesion-email">{{ usuarioActual?.email }}</span>
          </div>
          <button
            class="btn-brutal btn-brutal--danger admin-logout"
            @click="logout"
          >
            Cerrar sesión
          </button>
        </div>
      </header>

      <!-- Pestañas brutalistas -->
      <nav
        class="admin-tabs"
        role="tablist"
      >
        <button
          role="tab"
          :aria-selected="tabActiva === 'usuarios'"
          class="admin-tab"
          :class="{ 'admin-tab--activa': tabActiva === 'usuarios' }"
          @click="tabActiva = 'usuarios'"
        >
          Usuarios
          <span class="admin-tab-count">{{ usuarios.length }}</span>
        </button>

        <button
          role="tab"
          :aria-selected="tabActiva === 'contenido'"
          class="admin-tab"
          :class="{ 'admin-tab--activa': tabActiva === 'contenido' }"
          @click="tabActiva = 'contenido'"
        >
          Contenido
          <span class="admin-tab-count">{{ contenido.length }}</span>
        </button>
      </nav>

      <!-- ── Tab: Usuarios ─────────────────────────────────── -->
      <section
        v-if="tabActiva === 'usuarios'"
        class="admin-seccion"
        role="tabpanel"
      >
        <div class="admin-seccion-header">
          <h2 class="admin-seccion-titulo">
            Usuarios registrados
          </h2>
        </div>
        <TablaUsuarios :usuarios="usuarios" />
      </section>

      <!-- ── Tab: Contenido ────────────────────────────────── -->
      <section
        v-else-if="tabActiva === 'contenido'"
        class="admin-seccion"
        role="tabpanel"
      >
        <div class="admin-seccion-header">
          <h2 class="admin-seccion-titulo">
            Gestión de contenido
          </h2>
        </div>
        <TablaContenido
          :contenido="contenido"
          :autor-admin="usuarioActual?.name ?? ''"
          @crear="onCrearContenido"
          @editar="onEditarContenido"
          @borrar="onBorrarContenido"
          @auditoria="onAuditoria"
        />
      </section>

      <!-- ── Registro de auditoría (siempre visible en el panel) ── -->
      <div class="admin-auditoria">
        <RegistroAuditoria :historial="historialAuditoria" />
      </div>
    </div>
  </div>
</template>
