// src/components/Footer.jsx
import './Footer.css';

export default function Footer() {
  return (
    <footer className="footer">
      <div className="footer__inner">
        <p className="footer__big">Diseñado y programado a mano.</p>
        <div className="footer__meta">
          <p>UMAI — Tecnología Multimedial</p>
          <p>Programación Multimedial III · 2026</p>
          <p>
            React + Vite + CSS puro · sin frameworks de estilos, sin plantillas
          </p>
        </div>
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<script setup>
import './Footer.css';
</script>

<template>
  <footer class="footer">
    <div class="footer__inner">
      <p class="footer__big">
        Diseñado y programado a mano.
      </p>
      <div class="footer__meta">
        <p>UMAI — Tecnología Multimedial</p>
        <p>Programación Multimedial III · 2026</p>
        <p>Vue 3 + Vite + CSS puro · sin frameworks de estilos, sin plantillas</p>
      </div>
    </div>
  </footer>
</template>
